apiVersion: v1
data:
  DB_Host: c3FsMDE=
  DB_Password: cGFzc3dvcmQxMjM=
  DB_User: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secret
# Similar to configMaps but to store sensitive data
# Imperative
# - kubectl create secret generic <secret-name> --from-literal=<key>=<value> --from-literal=<key>=<value>
# - kubectl create secret generic <secret-name> --from-file=<path-to-file>
# data should be encrypted and not plain text
# To get the enconded value
# kubectl get secret app-secret -o yaml
# To encode values using base64 algorithm, secrets are NOT Encrypted
# - echo -n 'mysql' | base64
# - echo -n 'root' | base64
# - echo -n 'passwd' | base64
# To decode just add -- decode
# - echo 'LW4gcGFzc3dkCg==' | base64 --decode
# It's better to consider other services to manipulate secret values

# Lab
# - kubectl create secret generic db-secret --from-literal=DB_Host=sql01 --from-literal=DB_User=root --from-literal=DB_Password=password123 --dry-run=client -o yaml