apiVersion: v1
kind: Service
metadata:
  name: sql01
spec:
  selector:
    name: mysql
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mysql
  name: mysql
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: password123
    image: mysql:5.6
    name: mysql
    ports:
    - containerPort: 3306
      protocol: TCP