apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx 
  labels:
    name: nginx
    tier: frontend
spec:
  replicas: 3
  template:
      metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend
      spec:
        containers:
          - name: nginx
            image: nginx

# This is an old version of replica, replaced by replicaset
# kubectl create -f 02-replication-controller/replication-controller.yml
# IT WON'T WORK SINCE ITS OBSOLETE NOW