apiVersion: v1
kind: Service
metadata:
  name: my-service-nodeport
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: nginx      # SHOULD MATCH THE POD LABELS
    tier: frontend  # SHOULD MATCH THE POD LABELS
# Service uses radom algorithm to balance if there're multiple nodes
# kubectl create -f 05-services/service-nodeport.yml 
# minikube service my-service-nodeport