apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    metadata:
      name: nginx
      labels:
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
# Rollout and Versioning
# rollout creates a new deployment revision
# To see the revision and history of rollout
# - kubectl rollout status deployment/my-app-deployment
# - kubectl rollout history deployment/my-app-deployment

# Deployment strategies:
# 1.- Recreate: Destroys the PODS and create the new ones
# 2.- Rolling Update (default): Destroy and create new Pods one by one
# Using kubectl apply

# Rollback
# - kubectl rollback undo deployment/my-app-deployment

# Lab
# kubectl edit deploy frontend