apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  -  image: nginx
     name: nginx
  nodeName: node01 # Scheduling
# When a POD is created it add nodeName properties by default
# With no scheduler the pods continue un pending state
# Check if there's a scheduler:
# kubectl get pods -n kube-system